pipeline:
  dev:
      image: plugins/docker
      environment:
        - DOCKER_LAUNCH_DEBUG=true
      repo: 192.168.27.100:5555/jke/db
      registry: 192.168.27.100:5555
      insecure: true
      tags: 
        - dev
        - ${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}
      force_tag: true
      when:
        event: [push, pull_request, tag]
#
#  prod:
#      image: plugins/docker
#      environment:
#        - DOCKER_LAUNCH_DEBUG=true
#      repo: stackinabox/jke-db
#      registry: https://index.docker.io/v1/
#      email: 'tim.pouyer@gmail.com'
#      username: 'tpouyer'
#      password: '%your-password%'
#      tags: 
#        - latest
#        - ${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}
#        - prod-${DRONE_BUILD_NUMBER}
#      force_tag: true
#      when:
#        branch: master
#        event: [push, pull_request, tag]
